spring:
  application:
    name: Pharma Application
  #MongoDB Config
  data:
#    mongodb:
#      uri: mongodb+srv://admin:admin@clustermongo-fa8ao.mongodb.net/test?retryWrites=true&w=majority
#      host: localhost
#      port: 27017
#      database: mongo
#      repositories:
#        enabled: true
#  mvc:
#    static-path-pattern: /test/**

  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    #MySql Config
#    url: jdbc:mysql://localhost:3306/test2
#    username: root
#    password: rootroot
#    driver-class-name: com.mysql.jdbc.Driver
    #Postgresql Config
    url: jdbc:postgres://nvoxlrpenasdhy:5ae4a83ddad70160950d3fd78b7c736b9de6a1c2943269af0eb4adf5121d3e95@ec2-18-213-176-229.compute-1.amazonaws.com:5432/daschsfeg0qb7l
    username: nvoxlrpenasdhy
    password: 5ae4a83ddad70160950d3fd78b7c736b9de6a1c2943269af0eb4adf5121d3e95
 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
      
#server:
#  port: 8095

adata:
  test: string test
